export const RESET_CHARACTERS = "RESET_CHARACTERS";
export const CREATE_CHARACTER = "CREATE_CHARACTER";

export const SHOW_LINE_FORM = "SHOW_LINE_FORM";
export const HIDE_LINE_FORM = "HIDE_LINE_FORM";
export const DELETE_LINE = "DELETE_LINE";
export const UPDATE_LINE = "UPDATE_LINE";
export const CREATE_LINE = "CREATE_LINE";

export const PUSH_NOTICE = "PUSH_NOTICE";
export const POP_NOTICE = "POP_NOTICE";
