export const RESET_CHARACTERS = "RESET_CHARACTERS";
export const CREATE_CHARACTER = "CREATE_CHARACTER";

export const SELECT_LINE = "SELECT_LINE";
export const CLEAR_LINE_SELECTION = "CLEAR_LINE_SELECTION";
export const HOVER_LINE = "HOVER_LINE";
export const START_CONNECTION_SELECTION = "START_CONNECTION_SELECTION";
export const DELETE_LINE = "DELETE_LINE";
export const UPDATE_LINE = "UPDATE_LINE";
export const CREATE_LINE = "CREATE_LINE";

export const PUSH_NOTICE = "PUSH_NOTICE";
export const POP_NOTICE = "POP_NOTICE";

export const PRESS_ESCAPE = "PRESS_ESCAPE";
